Site_project/Site_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Site_project import settings
from catalog.views import HomeTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('authentication.urls')),
    path('cart/', include('cart.urls')),
    path('', HomeTemplateView.as_view(), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site_project/cart/urls.py
from django.contrib.auth import get_user_model
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<slug:product_slug>/', views.add, name='add'),
    path('change_quantity/<int:product_id>/', views.change_quantity, name='change_quantity'),
]

Site_project/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.category_view, name='category_view'),
    path('product/<slug:product_slug>/', views.product_view, name='product_view')
]

Site_project/catalog/models.py
import os.path
import uuid

from django.db import models

from catalog.validators import image_resolution_check_cart


class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='Описание')
    slug = models.SlugField(max_length=32, unique=True, default='test')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='Описание')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Цена')
    is_vegan = models.BooleanField(verbose_name="Вегатарианска?", default=False)
    slug = models.SlugField(max_length=32, unique=True, default='test')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество на складе')

    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="категория"
        )

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name


def get_file_path(instance, image_name: str):
    ext = image_name.split('.')[-1]
    new_name = f'{uuid.uuid4()}.{ext}'
    return os.path.join('products', new_name)


class ProductImage(models.Model):
    cart_image = models.ImageField(
        validators=[image_resolution_check_cart],
        upload_to=get_file_path,
        verbose_name="Изображение для таблицы",
        null=True,
        blank=True
    )
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    def __str__(self):
        return f'Изображение для {self.product.name}'

Site_project/catalog/views.py
from typing import Any

from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import Count
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView

from cart.models import CartProduct
from catalog.models import Category, Product


class HomeView(View):
    def get(self, request):
        cat = Category.objects.all()
        return render(
            request,
            'catalog/home.html',
            {"categories": cat}
        )


class HomeTemplateView(TemplateView):
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context: dict[str, Any] = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.annotate(Count('product'))
        return context


@login_required
def category_view(request: WSGIRequest, category_slug: str) -> HttpResponse:
    try:
        category: Category = (
            Category.objects
            .prefetch_related("product_set")
            .get(slug=category_slug)
        )
    except Category.DoesNotExist:
        raise Http404
    return render(
        request,
        'catalog/categories.html',
        {"category": category}
    )


@login_required
def product_view(request: WSGIRequest, product_slug: str) -> HttpResponse:
    try:
        product = (
            Product.objects
            .prefetch_related('productimage_set')
            .filter(slug=product_slug)
            .first()
        )
        is_in_cart = CartProduct.objects.filter(
            product=product,
            cart__user=request.user,
            cart__active=True).first()

        context = {
            'product': product,
            'is_in_cart': is_in_cart,
        }
    except Product.DoesNotExist:
        raise Http404
    return render(
        request,
        'catalog/product.html',
        context
    )

Site_project/catalog/templates/catalog/categories.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
    {% for product in category.product_set.all %}
        <div>
            <a href="{% url 'catalog:product_view' product.slug %}"> {{ product.name }} ({{ product.quantity }}) </a>
        </div>
    {% endfor %}
{% endblock %}

Site_project/catalog/templates/catalog/home.html
{% extends 'base.html' %}

{% block title %}Categories{% endblock %}

{% block content %}
    {% for category in categories %}
        <div>
            <a href="{% url 'catalog:category_view' category.slug %}"> {{ category.name }} </a>
        </div>
    {% endfor %}
{% endblock %}

Site_project/catalog/templates/catalog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<label for="email">email:</label>
<input id="email" type="email" name="email">

<br>
<label for="password">password:</label>
<input id="password" type="password" name="password">

<br>
<button type="submit">Login</button>
</body>
</html>

Site_project/catalog/templates/catalog/product.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <h3>
        {{ product.name }}
    </h3>
    <p>
        {{ product.description }}
    </p>

    {% if product.productimage_set.all %}
        {% for image in product.productimage_set.all %}
            <div>
                <img src="{{ image.image.url }}" alt="{{ product.name }}">
            </div>
        {% endfor %}
    {% endif %}

    {% if not is_in_cart %}
        <div>
            <a href="{% url 'cart:add' product.slug %}">Add To Cart</a>
        </div>
    {% else %}
        <div>
            <a href='{% url 'cart:cart' %}'>In Cart</a>
        </div>
    {% endif %}
{% endblock %}

Site_project/catalog/templates/catalog/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
<label for="email">email:</label>
<input id="email" type="email" name="email">

<br>
<label for="password">password:</label>
<input id="password" type="password" name="password">

<br>
<label for="repeat_password">repeat password:</label>
<input id="repeat_password" type="email" name="repeat_password">

<br>
<label for="date_of_birth">date of birth:</label>
<input id="date_of_birth" type="email" name="date_of_birth">

<br>
<label for="photo">photo:</label>
<input id="photo" type="file" name="photo">

<br>
<label for="description">description:</label>
<textarea id="description" name="description"></textarea>

<br>
<button type="submit">Registration</button>
</body>
</html>