Site_project/Site_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Site_project import settings
from catalog.views import HomeTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('authentication.urls')),
    path('cart/', include('cart.urls')),
    path('', HomeTemplateView.as_view(), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site_project/authentication/urls.py
from django.urls import path

from . import views

app_name = "authentication"

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

Site_project/cart/urls.py
from django.contrib.auth import get_user_model
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<slug:product_slug>/', views.add, name='add'),
    path('change_quantity/<int:product_id>/', views.change_quantity, name='change_quantity'),
]

Site_project/authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.ImageField(verbose_name="Аватарка", blank=True, null=True)
    email = models.EmailField(verbose_name="email", unique=True)

Site_project/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.core.exceptions import ValidationError
from django.db.models import Q

User = get_user_model()


class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, label='Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Повторите пароль')

    class Meta:
        model = User
        fields = ['username', 'email', 'avatar']
        labels = {
            'username': 'Имя пользователя',
            'email': 'Email'
        }

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise ValidationError(
                'Пароли должны совпадать'
            )
        return self.cleaned_data['password2']

    def clean(self):
        user = User.objects.filter(
            Q(username=self.cleaned_data['username'])
            | Q(email=self.cleaned_data['email'])
        ).first()

        if user:
            raise ValidationError('Пользователь с такими учетными данными уже существует')

        return super().clean()


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

    def clean(self):
        user = authenticate(
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password']
        )
        if not user:
            raise ValidationError('Введенные данные не верны')
        return self.cleaned_data

Site_project/authentication/views.py
from django.contrib.auth import (
    get_user_model,
    authenticate,
    login as login_user,
    logout as logout_user
)
from django.shortcuts import render, redirect
from django.urls import reverse

from authentication.forms import RegistrationForm, LoginForm

User = get_user_model()


def registration(request):
    if request.user.is_authenticated:
        return redirect(reverse('catalog:home'))
    if request.method == "POST":
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password2'])
            user.save()
            return redirect(reverse('catalog:home'))
    else:
        form = RegistrationForm()

    return render(
        request,
        'authentication/registration.html',
        {'form': form}
    )


def login(request):
    if request.user.is_authenticated:
        return redirect(reverse('catalog:home'))
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )
            if user:
                login_user(request, user)
                return redirect(reverse('catalog:home'))
    else:
        form = LoginForm()
    return render(
        request,
        'authentication/login.html',
        {'form': form}
    )


def logout(request):
    logout_user(request)
    return redirect(reverse('catalog:home'))

Site_project/authentication/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    {% load static %}
    {% load widget_tweaks %}
    <link rel="stylesheet" href="{% static 'authentication/styles.css' %}">
</head>
<body>
<form
        method="post"
        action="{% url 'authentication:login' %}"
>
    {% csrf_token %}

    {% for field in form %}
        <div class="form-row">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                    <span class="error-message">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="error-message">{{ error }}</p>
        {% endfor %}
    {% endif %}

    <button type="submit">Войти</button>

    <p>Если у вас нет учетной записи нужно зарегистрироваться</p>
    <a href="{% url 'authentication:registration' %}">Зарегистрироваться</a>
</form>
</body>
</html>

Site_project/authentication/templates/authentication/registration.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    {% load static %}
    {% load widget_tweaks %}
    <link rel="stylesheet" href="{% static 'authentication/styles.css' %}">
</head>
<body>
<form
        method="post"
        action="{% url 'authentication:registration' %}"
        enctype="multipart/form-data"
>
    {% csrf_token %}

    {% for field in form %}
        <div class="form-row">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                    <span class="error-message">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="error-message">{{ error }}</p>
        {% endfor %}
    {% endif %}

    <button type="submit">Зарегистрироваться</button>

    <p>Если аккаунт?</p>
    <a href="{% url 'authentication:login' %}">Войти</a>
</form>
</body>
</html>