Site_project/Site_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Site_project import settings
from catalog.views import HomeTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('authentication.urls')),
    path('cart/', include('cart.urls')),
    path('', HomeTemplateView.as_view(), name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site_project/cart/urls.py
from django.contrib.auth import get_user_model
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<slug:product_slug>/', views.add, name='add'),
    path('change_quantity/<int:product_id>/', views.change_quantity, name='change_quantity'),
]

Site_project/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from catalog.models import Product
from django.conf import settings


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)


class CartProduct(models.Model):
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(default=1)


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True)


class Order(models.Model):
    user = models.ForeignKey('Customer', on_delete=models.CASCADE)
    products = models.ManyToManyField('CartProduct')
    date = models.DateField(auto_now=True)

Site_project/cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse

from catalog.views import HomeView
from .models import Cart, CartProduct, Order, Customer
from catalog.models import Product


@login_required
def add(request, product_slug):
    slug_product = Product.objects.get(slug=product_slug)
    new_cart, _ = Cart.objects.get_or_create(user=request.user, active=True)
    new_product, _ = CartProduct.objects.get_or_create(product=slug_product, cart=new_cart)
    return redirect(reverse('catalog:home'))


@login_required
def cart(request):
    user = request.user
    customer, _ = Customer.objects.get_or_create(user=user)
    customer.save()
    cart_id = Cart.objects.filter(user_id=user.id).first()
    cart_products = CartProduct.objects.select_related('product').filter(cart_id=cart_id)
    full_price = total_sum(cart_products)
    if not cart:
        return redirect(reverse('catalog:home'))
    context = {'cart_products': cart_products,
               'full_price': full_price}
    return render(request, 'cart/cart.html', context)


def total_sum(cart_products):
    price = 0
    for product in cart_products:
        quantity = product.quantity
        price += product.product.price*quantity
    return round(price, 2)


@login_required
def change_quantity(request, product_id):
    cart_product = CartProduct.objects.get(id=product_id)
    quantity_from_html = int(request.POST.get('quantity'))
    if quantity_from_html <= cart_product.product.quantity:
        cart_product.quantity = quantity_from_html
        cart_product.save()
    return redirect(reverse('cart:cart'))

Site_project/cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block title %}Корзина{% endblock %}

{% block content %}

    <table>
        <tr>
            <th>Наименование товара</th>
            <th>Цена</th>
            <th>Количество</th>
        </tr>
        {% for product in cart_products %}
            <tr>
                <td>{{ product.product.name }}</td>
                <td>{{ product.product.price }}</td>
                <td>{{ product.quantity }}</td>
                <td>
                    <form method="post" action="{% url 'cart:change_quantity' product.id %}">
                        {% csrf_token %}
                        <div>
                            <input name="quantity"
                                   max="{{ product.product.quantity }}"
                                   value="{{ product.quantity }}">
                            <button href="{% url 'cart:change_quantity' product.id %}">Change</button>
                        </div>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>

    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Total</strong></td>
        <td><strong>{{ full_price }}</strong></td>
    </tr>

{% endblock %}